### PR TITLE
Add support for Reason / OCaml

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by zth** [comment]
Great 😄 ! @anmonteiro would you mind adding an example `.ml` and `.re` file in `compiler/test-project-res` that has some dummy query in them, and then rebuild and run the compiler in that folder (`cd compiler/test-project-res && cargo build && ../target/debug/relay`)? You can commit the generated files. This is a simple "test" to ensure operations are properly extracted etc.

**Comment by anmonteiro** [comment]
Added the requested files

**Comment by zth** [comment]
@anmonteiro did you also run the compiler? if so, the changes doesn't seem to work - the compiler should pick up the queries in those files and spit out generated files, if everything works.

**Comment by anmonteiro** [comment]
Should I commit the generated files too? Yes, they got generated locally.

**Comment by zth** [comment]
Yes, i use them to spot regressions, so it's nice to have them committed. Thanks!

**Pull request merged**
